default_agent: ai_shopping_assistant
agents:
  ai_shopping_assistant:
    name: ai_shopping_assistant
    entrypoint: C:/Projects/ai_shopping_assistant/my-agent/main.py
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Projects\ai_shopping_assistant\my-agent
    aws:
      execution_role: arn:aws:iam::799440957487:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-9169fbc0d9
      execution_role_auto_create: false
      account: '799440957487'
      region: us-east-1
      ecr_repository: 799440957487.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-ai_shopping_assistant
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: ai_shopping_assistant-qJc8zT395J
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:799440957487:runtime/ai_shopping_assistant-qJc8zT395J
      agent_session_id: 3497fbc3-4139-4094-b482-8a6f50d67027
    codebuild:
      project_name: bedrock-agentcore-ai_shopping_assistant-builder
      execution_role: arn:aws:iam::799440957487:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-9169fbc0d9
      source_bucket: bedrock-agentcore-codebuild-sources-799440957487-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: ai_shopping_assistant_mem-r4ItYh4lLR
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:799440957487:memory/ai_shopping_assistant_mem-r4ItYh4lLR
      memory_name: ai_shopping_assistant_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
